// this is in a separate JS file so that Node can import it too
export const preambleKeywords = [
    "title",
    "artist",
    "songbooks",
    "key",
    "date_added",
    "language",
    "tempo",
    "capo",
    "range",
    "start_melody",
    "prompt_model",
    "prompt_id",
    "image_model",
    "pdf_filenames",
];

// fields generated by the load_songs.mjs script
export const generatedFields = [
    "availableIllustrations",
    "chordproFile",
    "contentHash",
]

export const JS2chordproKeywords = {
    title: "title",
    artist: "artist",
    songbooks: "songbooks",
    key: "key",
    dateAdded: "date_added",
    language: "language",
    tempo: "tempo",
    capo: "capo",
    range: "range",
    startMelody: "start_melody",
    promptModel: "prompt_model",
    promptId: "prompt_id",
    imageModel: "image_model",
    pdfFilenames: "pdf_filenames",
};


export const chordpro2JSKeywords = Object.fromEntries(
    Object.entries(JS2chordproKeywords).map(([key, value]) => [value, key])
);