name: Generate Images

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          
      - name: Create secrets file
        run: |
          echo "hugging_face_token: ${{ secrets.HUGGING_FACE_TOKEN }}" > secrets.yaml
          echo "openai:" >> secrets.yaml
          echo "  api_key: ${{ secrets.OPENAI_API_KEY }}" >> secrets.yaml
          echo "  organization_id: ${{ secrets.OPENAI_ORGANIZATION_ID }}" >> secrets.yaml
          echo "  project_id: ${{ secrets.OPENAI_PROJECT_ID }}" >> secrets.yaml
      
      - name: Run image generation script
        run: python scripts/generate_images.py
        
      - name: Check for changes
        id: check_changes
        run: |
          git add songs/illustrations songs/illustrations_thumbnails songs/image_prompts
          git status --porcelain | wc -l | xargs -I {} echo "CHANGES={}" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.CHANGES != '0'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update song illustrations [skip ci]"
          git push