name: Sync Main to CF-Workers

on:
  workflow_run:
    workflows: ["Format songs & Generate Images"]
    types:
      - completed
    branches: [ main ]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    # Only run if the triggering workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Switch to cf-workers branch
      run: |
        git checkout cf-workers || git checkout -b cf-workers
    
    - name: Copy songs directory from main
      run: |
        # Remove existing songs directory if it exists
        rm -rf songs/
        
        # Copy songs directory from main branch
        git checkout origin/main -- songs/
        
        # Check if there are any changes to commit
        if ! git diff --quiet --cached; then
          git add songs/
          git commit -m "Auto-sync: Update songs directory from main"
        else
          echo "No changes to sync in songs directory"
        fi
    
    - name: Push changes to cf-workers
      run: |
        git push origin cf-workers
